var hiddentypes = { 
	130:"Rechargeable batteries",
	14:"Plastics",
	146:"Hardbacked catalogues",
	148:"Plasterboard",
	149:"Newspaper",
	150:"Plastic milk bottles(no tops)",
	151:"Tetra Pak",
	152:"Other Plastics",
	19:"Household and garden chemicals",
	20:"Cooking oil",
	24:"Asbestos",
	31:"Household plastic packaging",
	37:"Toner cartridges",
	44:"Soil",
	5:"Gas bottles",
	52:"Telephone directories",
	53:"Food scraps &amp; leftovers",
	56:"Kitchen waste",
	57:"Pet food",
	80:"Paint tins",
	81:"Brown materials",
	83:"Green materials",
	84:"Cookware &amp; cutlery"
}