var visibletypes = { 
	1:"Household metal packaging",
	11:"Clothing",
	12:"Wood &amp; timber",
	13:"Yellow pages",
	145:"All household waste",
	16:"Plastic bottles",
	17:"Cartons",
	18:"Books",
	2:"Cardboard",
	21:"Plastic bags",
	22:"Tyres",
	23:"Furniture",
	25:"DVDs, CDs, videos &amp; tapes",
	26:"Energy saving lightbulbs &amp; fluorescent tubes",
	27:"Paint",
	29:"Aerosol cans",
	3:"Engine oil",
	30:"Large electrical appliances",
	32:"Batteries",
	33:"Hard-core &amp; rubble",
	34:"Printer cartridges",
	38:"Car &amp; engine batteries",
	4:"Garden waste",
	40:"Fridges &amp; freezers",
	41:"Aluminium foil",
	42:"Mobile phones",
	43:"Shoes",
	45:"Small appliances",
	46:"TVs &amp; monitors",
	49:"Mixed textiles &amp; clothes",
	51:"Spectacles",
	6:"Glass bottles and jars",
	7:"Paper",
	8:"Household metal and packaging",
	82:"Plate Glass",
	9:"Scrap metal"
}