var types = { 
	1:"Household metal packaging",
	2:"Cardboard",
	3:"Engine oil",
	4:"Garden waste",
	5:"Gas bottles",
	6:"Glass bottles and jars",
	7:"Paper",
	8:"Household metal and packaging",
	9:"Scrap metal",
	11:"Clothing",
	12:"Wood &amp; timber",
	13:"Yellow pages",
	14:"Plastics",
	16:"Plastic bottles",
	17:"Cartons",
	18:"Books",
	19:"Household and garden chemicals",
	20:"Cooking oil",
	21:"Plastic bags",
	22:"Tyres",
	23:"Furniture",
	24:"Asbestos",
	25:"DVDs, CDs, videos &amp; tapes",
	26:"Energy saving lightbulbs and fluorescent tubes",
	27:"Paint",
	29:"Aerosol cans",
	30:"Large electrical appliances",
	31:"Household plastic packaging",
	32:"Batteries",
	33:"Hard-core &amp; rubble",
	34:"Printer cartridges",
	37:"Toner cartridges",
	38:"Car &amp; engine batteries",
	40:"Fridges &amp; freezers",
	41:"Aluminium foil",
	42:"Mobile phones",
	43:"Shoes",
	44:"Soil",
	45:"Small appliances",
	46:"TVs &amp; monitors",
	49:"Mixed textiles and clothes",
	51:"Spectacles",
	52:"Telephone directories",
	53:"Food scraps &amp; leftovers",
	56:"Kitchen waste",
	57:"Pet food",
	80:"Paint tins",
	81:"Brown materials",
	82:"Plate Glass",
	83:"Green materials",
	84:"Cookware and cutlery",
	130:"Rechargeable batteries",
	145:"All household waste",
	146:"Hardbacked catalogues",
	148:"Plasterboard",
	149:"Newspaper",
	150:"Plastic milk bottles (no tops)",
	151:"Tetra Pak",
	152:"Other Plastics"
}